name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
    
    - name: Setup Google Cloud Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy gcf-sample \
          --trigger-http \
          --region asia-northeast1 \
          --runtime nodejs20 \
          --entry-point helloHttp \
          --allow-unauthenticated